#version: '3'
services:

  ace-db:
    image: mysql:8.0
    container_name: ace-db
    env_file:
      - ./docker.env
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306/tcp"
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  ace-server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: acemulator/ace:latest
    depends_on:
      ace-db:
        condition: service_healthy
    container_name: ace-server
    env_file:
      - ./docker.env
    volumes:
      - ../Config:/ACE/Config
      - ../Content:/ACE/Content
      - ../Dats:/ACE/Dats
      - ../Logs:/ACE/Logs
      - ../Mods:/ACE/Mods
    ports:
      - "9000-9001:9000-9001/udp"
    stdin_open: true
    #restart: unless-stopped
    restart: on-failure
